//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBookService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public int EmailTypeId { get; set; }
        public string EmailTypeCode { get; set; }
        public string EmailTypeDescription { get; set; }
        public System.DateTime EmailTypeModified { get; set; }
    }
}
