//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBookService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContact
    {
        public int UserContactId { get; set; }
        public int UsersId { get; set; }
        public int ContactId { get; set; }
        public byte IsUser { get; set; }
        public System.DateTime UserContactModified { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual User User { get; set; }
    }
}
